### ISSUE TITLE
cartographer_assets_writer and rosbag_validate: Failed to find match for field 'intensity'.

### ISSUE THREAD

**Issue by kajep09** [googlecartographer/cartographer_ros#1018]
I have a problem with the assets_writer and rosbag_validate reporting the warning `Failed to find match for field 'intensity'.` while running it with my bagged data. I don't have the possibility to upload the bagfiles at the moment, but I have included the output of the header of my PointCloud2 topic and for comparison also included one from one of the official 3d_backpack rosbags (b3-2016-04-05-15-51-36.bag)

As you can see there is indeed an intensity field in the fields part of the message and I can visualize the pointcloud with intensity colouring in rviz.

However, in the b3-2016-04-05-15-51-36.bag I can see that the intensity has datatype: 7 (uint8 FLOAT32 = 7) and my intensity data has datatype: 4 (uint8 UINT16  = 4). See http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/PointField.html

Do you know if the data type of the intensity data has anything to do with the assets_writer and rosbag_validate complaining?

Link is a gist of running rosbag_validate (excluding thousands of lines of the warning):
`rosrun cartographer_ros cartographer_rosbag_validate -bag_filename=ouster_ros.bag`
https://gist.github.com/kajep09/91869019925676b69e4ea5e6025277b1

```
header: 
  seq: 1269
  stamp: 
    secs: 1536832001
    nsecs: 178107976
  frame_id: "os1"
height: 1
width: 65536
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "t"
    offset: 16
    datatype: 7
    count: 1
  - 
    name: "reflectivity"
    offset: 20
    datatype: 4
    count: 1
  - 
    name: "intensity"
    offset: 22
    datatype: 4
    count: 1
  - 
    name: "ring"
    offset: 24
    datatype: 2
    count: 1
is_bigendian: False
point_step: 32
row_step: 2097152
```

```
header: 
  seq: 0
  stamp: 
    secs: 1459871511
    nsecs: 702640300
  frame_id: "horizontal_vlp16_link"
height: 1
width: 384
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "intensity"
    offset: 12
    datatype: 7
    count: 1
is_bigendian: False
point_step: 16
row_step: 6144
```
