### ISSUE TITLE
odom coordinate system moves in RViz with velodyne VLP16

### ISSUE THREAD

**Issue by StarUnderNight** [googlecartographer/cartographer_ros#1788]
Hello， I used vlp-16 radar for scanning and mapping on turbobot3. When I specified the target position, the odom coordinate system moved in the opposite direction of the target position, map and base_ Footprint did not move, as shown in the figure, odom moved from position A to position B. But in gazebo, the car will move forward.
![image](https://github.com/cartographer-project/cartographer_ros/assets/16272346/4fb8602b-4875-435f-988d-621b281d73f2)
![image](https://github.com/cartographer-project/cartographer_ros/assets/16272346/6ec5dbd7-9a12-4011-aa1b-71101e770b1d)
this is my lua config
```lua
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "imu",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = false,
  use_pose_extrapolator = true,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 0,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 1,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 1

MAP_BUILDER.use_trajectory_builder_3d = true
MAP_BUILDER.num_background_threads = 7
POSE_GRAPH.optimization_problem.huber_scale = 5e2
POSE_GRAPH.optimize_every_n_nodes = 320
POSE_GRAPH.constraint_builder.sampling_ratio = 0.03
POSE_GRAPH.optimization_problem.ceres_solver_options.max_num_iterations = 10
POSE_GRAPH.constraint_builder.min_score = 0.62
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.66

return options

```
this is costmap_common_params.yaml
```yaml
footprint: [[-3.0, -1.5], [-3.0, 1.5], [2.4, 1.5], [2.4, -1.5]]
obstacle_layer:
  enabled: true
  obstacle_range: 10.0
  raytrace_range: 10.5
  track_unknown_space: false
  combination_method: 1
  z_resolution: 0.3
  z_voxels: 10
  publish_voxel_map: true
  origin_z: 0.0
  max_obstacle_height: 2.8

  observation_sources: bump1
  bump1: {
    data_type: PointCloud2,
    topic: velodyne_points,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.2,
    max_obstacle_height: 1.9
  }
inflation_layer:
  enabled:              true
  cost_scaling_factor:  3  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.2  # max. distance from an obstacle at which costs are incurred for planning paths.
static_layer:
  enabled: true
```
this is global_costmap
```yaml
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 2.0
  plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
```
this is local_costmap_params.yaml
```yaml
local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  
  rolling_window: true
  width: 8
  height: 8
  resolution: 0.05
  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
```
