### ISSUE TITLE
question of start_trajectory 

### ISSUE THREAD

**Issue by eithwa** [googlecartographer/cartographer_ros#1791]
Hello,

I would like to ask whether the start_trajectory function using rosservice has the same effect as the cartographer_start_trajectory node, as the master branch currently does not contain the cartographer_start_trajectory node.

Additionally, I'd like to inquire about the relative_to_trajectory_id parameter. If it is set to 0, does it refer to the first set of points in the trajectory_node_list to set the coordinates?

Currently, I am facing an issue where I use this function to update the coordinates to position: {x: -14.729079, y: 0.266100, z: 0.0}, but after updating the coordinates, the position becomes {x:-14.723, 0.433098,z:0.0},The y-axis position is about 20 cm away from my expectation,
 trajectory id 0 is as follows:

```
sdmarkers:
header:
  seq: 0
  stamp:
    secs: 1596
    nsecs: 751000000
  frame_id: "map"
ns: "Trajectory 0"
id: 0
type: 4
action: 0
pose:
  position:
    x: 0.0
    y: 0.0
    z: 0.05
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
scale:
  x: 0.07
  y: 0.0
  z: 0.0
color:
  r: 0.207129895687
  g: 0.115499980748
  b: 0.769999980927
  a: 1.0
lifetime:
  secs: 0
  nsecs: 0
frame_locked: False
points:
  -
    x: 0.00551946445911
    y: -0.00345368672909
    z: 0.0
  -
```
Is there any way to update the coordinates accurately?
