### ISSUE TITLE
Cartographer 2D SLAM Map Frame Stabilization Issue

### ISSUE THREAD

**Issue by ZU-0828** [googlecartographer/cartographer_ros#1832]
https://github.com/cartographer-project/cartographer_ros/assets/174670913/4f5bd068-f291-4c9d-b00b-2dba300f0340

Hello, I am a beginner user of Cartographer.

I used the backpack_2d.launch file to operate with 2D LiDAR and IMU sensor topics. It worked, but after a few seconds, the angle and xyz coordinates of the map frame started to rotate and move arbitrarily. Additionally, although I am not sure if it is directly related to this issue, the following message kept appearing as the map frame rotated:
`[cartographer_node-2] [INFO] [1720346086.622282686] [cartographer logger]: I20240707 18:54:46.-2147483648  6902 collated_trajectory_builder.cc:81] imu rate: 88.08 Hz 1.14e-02 s +/- 2.76e-03 s (pulsed at 99.94% real time)
[cartographer_node-2] [INFO] [1720346086.622367445] [cartographer logger]: I20240707 18:54:46.-2147483648  6902 collated_trajectory_builder.cc:81] scan rate: 72.98 Hz 1.37e-02 s +/- 1.17e-02 s (pulsed at 100.86% real time)
`

TF Tree:
![image](https://github.com/cartographer-project/cartographer_ros/assets/174670913/b1b8415b-45dc-45ec-a447-8e643be47118)

I checked the relationship between the frames through the `URDF` file, and there doesn't seem to be anything unusual. Could this issue be caused by the sensor rate? Has anyone experienced a similar issue? I don't know how to resolve this.

**Comment by ZU-0828** [comment]
Hello everyone, I checked several things to resolve this issue and found that the topic of the IMU sensor was incorrect. First, I connected an extra MPU6050 and found that the issue was resolved. Then, by comparing the IMU topics, I discovered a problem with the BNO055/IMU topic.

```
BNO055/IMU topic:
orientation:
  x: 0.008300730274201034
  y: -0.008056591148489238
  z: -0.0007324173771353854
  w: 0.9999328241340849
orientation_covariance:
- 0.0159
- 0.0
- 0.0
- 0.0
- 0.0159
- 0.0
- 0.0
- 0.0
- 0.0159
angular_velocity:
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance:
- 0.04
- 0.0
- 0.0
- 0.0
- 0.04
- 0.0
- 0.0
- 0.0
- 0.04
linear_acceleration:
  x: 0.03
  y: -0.15
  z: -0.27
linear_acceleration_covariance:
- 0.017
- 0.0
- 0.0
- 0.0
- 0.017
- 0.0
- 0.0
- 0.0
- 0.017

```

Here, it can be seen that the acceleration on the Z-axis is close to 0 instead of being close to 9.806. Then, by checking the BNO055/imu_raw topic,
```
BNO055/imu_raw topic:
orientation:
  x: 0.0
  y: 0.0
  z: 0.0
  w: 1.0
orientation_covariance:
- 0.0159
- 0.0
- 0.0
- 0.0
- 0.0159
- 0.0
- 0.0
- 0.0
- 0.0159
angular_velocity:
  x: 0.0
  y: -0.0033333333333333335
  z: 0.0011111111111111111
angular_velocity_covariance:
- 0.04
- 0.0
- 0.0
- 0.0
- 0.04
- 0.0
- 0.0
- 0.0
- 0.04
linear_acceleration:
  x: 0.2
  y: 0.24
  z: 9.72
linear_acceleration_covariance:
- 0.017
- 0.0
- 0.0
- 0.0
- 0.017
- 0.0
- 0.0
- 0.0
- 0.017

```

I verified that the values needed for the Cartographer were correct by checking the BNO055/imu_raw topic, and connected the BNO055/imu_raw to resolve the map frame issue. It was a very simple issue.

If you have any issues with the map frame and are using an IMU, I recommend checking the IMU topic first. Have a good day.
