### ISSUE TITLE
Adding ArduPilot IMU and odom data

### ISSUE THREAD

**Issue by elgarbe** [googlecartographer/cartographer_ros#790]
I have an ASV driven by a pixhawk, running ardurover, and a raspberry pi 3 as a companion computer.
Connected to the PI there is an hokuyo lidar. 
Thank to @cschuet I get cartographer mapping with just LIDAR data.
But now I want to add IMU and odometry data provided by ArduRover through Mavros.

This is IMU msg
```
header: 
  seq: 324
  stamp: 
    secs: 1455208218
    nsecs: 779422082
  frame_id: "base_link"
orientation: 
  x: -0.0196528313319
  y: -0.0373457958945
  z: 0.507724505298
  w: -0.860485261041
orientation_covariance: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
angular_velocity: 
  x: 0.000183623924386
  y: -0.000642724335194
  z: -2.97694932669e-05
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: -0.65704555
  y: -0.02941995
  z: 10.0223963
linear_acceleration_covariance: [8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08]
---
```
this is odom msg:

```
header: 
  seq: 1556
  stamp: 
    secs: 1455208296
    nsecs: 310980854
  frame_id: "map"
child_frame_id: "base_link"
pose: 
  pose: 
    position: 
      x: -0.005535364151
      y: -0.267928063869
      z: 0.0810627788305
    orientation: 
      x: -0.0192797667306
      y: -0.0368807024663
      z: 0.50707105612
      w: -0.860898976899
  covariance: [1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06]
twist: 
  twist: 
    linear: 
      x: -0.00152582221037
      y: -0.0375590241358
      z: -0.00955859516847
    angular: 
      x: -7.68475001678e-06
      y: -0.000235044397414
      z: 0.00026510679163
  covariance: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001]
---
```
and this is scan topic

```
---
header: 
  seq: 532
  stamp: 
    secs: 1455208419
    nsecs: 333519654
  frame_id: "laser"
angle_min: -2.35619449615
angle_max: 2.09234976768
angle_increment: 0.00613592332229
time_increment: 9.76562732831e-05
scan_time: 0.10000000149
range_min: 0.019999999553
range_max: 5.59999990463
ranges: [0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239, 0.01899999938905239,
```

So, my frames are
tracking_frame = base_link (the frame where the IMU are, right?)
published_frame = base_link???
odom_frame = ????

I'm very confuse about frames of my msg...
