### ISSUE TITLE
which part of odom msg cartographer use?

### ISSUE THREAD

**Issue by elgarbe** [googlecartographer/cartographer_ros#795]
this is my odom mesage:

```
header: 
  seq: 1556
  stamp: 
    secs: 1455208296
    nsecs: 310980854
  frame_id: "map"
child_frame_id: "base_link"
pose: 
  pose: 
    position: 
      x: -0.005535364151
      y: -0.267928063869
      z: 0.0810627788305
    orientation: 
      x: -0.0192797667306
      y: -0.0368807024663
      z: 0.50707105612
      w: -0.860898976899
  covariance: [1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06]
twist: 
  twist: 
    linear: 
      x: -0.00152582221037
      y: -0.0375590241358
      z: -0.00955859516847
    angular: 
      x: -7.68475001678e-06
      y: -0.000235044397414
      z: 0.00026510679163
  covariance: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001]
---
```

Wich part of this msg is used by cartographer?
